

# Compare by Department 

```{r byDepartment.r.dtRESULT}

r.dtRESULT <- reactive({
  # setkeyv(dtAll, PSES_ID_COLS)
  # dtAll[ as.list(r.myID())][ QUESTION==r.myQ() & SURVEYR==r.myYear()]
  
  
  dtResultsAll <<- dtAll[Question.Abbreviated==input$question]; 
  setkeyv(dtResultsAll, PSES_ID_COLS)
  dtRESULT <<- dtResultsAll[as.list(r.myID())] 
  
  # .. input$showchildren: dtResultsBelow----
  
  # myID <<- r.myID()
  
  if (id1() == 0) {
    dtRESULT <<- dtResultsAll[LEVEL2ID==0] %>% 
      rbind(dtRESULT)
  } else {
    
    if (input$showchildren) {
      setkeyv(dtResultsAll, PSES_ID_COLS[1:(which.min(myID)-1)])
      
      dtRESULT <<- dtResultsAll[as.list(myID[1:(which.min(myID)-1)])] %>% 
        rbind(dtRESULT)
    }
    
    # .. input$showparents: dtResultsAbove----
    if (input$showparents) {
      
      dtRESULT <<- dtResultsAll[
        (LEVEL1ID == 0 | LEVEL1ID == myID[1] ) & 
          (LEVEL2ID == 0 | LEVEL2ID == myID[2]) & 
          (LEVEL3ID == 0 | LEVEL3ID == myID[3]) & 
          (LEVEL4ID == 0 | LEVEL4ID == myID[4] )& 
          (LEVEL5ID == 0 | LEVEL5ID == myID[5]  ) 
        ] %>% rbind(dtRESULT)
    }
  }
  
  dtRESULT <<- dtRESULT %>% unique()
  setkeyv(dtRESULT,COLS_PSES)
  
  
  
  #sapply(dtRESULT,typeof)
  #  dtRESULT[, SURVEYR:=as.ordered(SURVEYR)]
  
  
  # .. input$sortby -----
  if (input$sortby =="name"){
    dtRESULT[ , Organization := reorder(Organization, Organization)]
    dtRESULT[ , Organization := reorder(Organization, IDlevel)]
  } else if (input$sortby =="number of responses"){
    dtRESULT[ , Organization := reorder(Organization, ANSCOUNT)]
    dtRESULT[ , Organization := reorder(Organization, IDlevel)] 
  } else if (input$sortby =="score"){
    dtRESULT[ , Organization := reorder(Organization , -SCORE100) ]
    dtRESULT[ , Organization := reorder(Organization , IDlevel)]
  } else { # (input$sortby =="rank"){ 
    dtRESULT[ , Organization := reorder(Organization , -RANK_GoC) ]
    dtRESULT[ , Organization := reorder(Organization , IDlevel)]
  } 
  
  
  # .. input$overlay -----
  
  if (input$overlay =="name"){
    dtRESULT[ , overlay := AADD]
  } else if (input$overlay =="number of responses"){
    dtRESULT[ , overlay := ANSCOUNT]
  } else if (input$overlay =="score"){
    dtRESULT[ , overlay := SCORE100]
  } else if (input$overlay =="rank"){ 
    dtRESULT[ , overlay := RANK_GoC]
  } else if (input$overlay =="rankAgency"){ 
    dtRESULT[ , overlay := RANK_Agency]
  } else if (input$overlay =="year"){ 
    dtRESULT[ , overlay := SURVEYR]
  } else { #nothing
    dtRESULT[ , overlay := ""]
  }
  
  
  
  # .. filterbyrank -----
  
  if (input$level3>0)  {
    dtRESULT <<- dtRESULT [RANK_Agency< input$filterbyrank[2] & RANK_Agency >input$filterbyrank[1] ]
  } else {
    dtRESULT <<- dtRESULT [RANK_GoC < input$filterbyrank[2] & RANK_GoC >input$filterbyrank[1] ]
  }
  
  
  
  
  # .. filterbygradient -----  
  
  dtRESULT <<- dtRESULT [SCORE_vs_2011 < input$filterbygradient[2] & SCORE_vs_2011 >input$filterbygradient[1] ]
  
  
  #  dtRESULT <<- dtRESULT[SURVEYR==input$year]
  dtRESULT
  
})
```


<!-- ## Row 1 {data-height=100}  -->



## Row 2 {.tabset .tabset-fade}



<!-- ### By Question  {data-height=800}  -->

<!-- ### Score by Department {data-height=800}  -->
### Graph view {data-height=800} 
<!-- ### Side by side comparison: graph {data-height=800}  -->


<!-- #### PLOT  -->

```{r plot.Depts_vs_Scores}

# selectInput('question', "Select Question:" ,
#             width="100%",
#             choices = dtQuestions$Question %>% unique
# )

renderPlot({
  
  
  # plotDepts_vs_Scores(input) +
  
  ggplot(r.dtRESULT()[SURVEYR==input$year],
  )  + 
    theme_bw() + theme(legend.position = "bottom")  +
    scale_x_continuous(breaks=(3:9)*10, limit=c(30,90)) +
    geom_vline(aes(xintercept=50), col="black", linetype=4) +
    labs(
      x="Score = Positive responses / All responses (%)",
      y=NULL,
      caption = paste0("Public Service Employee Survey Results\nLicense: Open Government Licence - Canada\n Generated", #  on ", format(Sys.time(), "%d %B, %Y"), 
                       " by iTrack (https://itrack.shinyapps.io/PSES)")
    )   +
    
    annotation_raster(image_smileys, xmin = 46, xmax = 54, ymin = 0.2, ymax = 1.8) +
         geom_vline(aes(xintercept=dtRESULT[SURVEYR==input$year & IDlevel==0]$SCORE100), linetype=4,  col="black") +
    
    # geom_point(aes(SCORE100, Organization, col=SURVEYR),size=10, alpha=0.2) +
    geom_label(aes(SCORE100, Organization, col=as.ordered(IDlevel),
                    fill=as.ordered(SURVEYR),
                   label=overlay
    ), alpha=0.2) +
    # scale_fill_brewer(palette = "Blues")  +
    # guides(size="none") +
    guides(colour="none") +
    # guides(fill="none")
    guides(fill= guide_legend("SURVEY YEAR")) + 
    #guides(colour = guide_legend("Public Service average")) +
    
    
    labs(
      # title=input$question,
      title=dtQuestions[QUESTION == r.myQ()]$Question,
      #title=paste0(input$year, " Public Service Employee Survey Results"),
      # subtitle=paste0(dtQuestions[Question == input$question]$Question,"\nNumber of responses is indicated in the box"),
      subtitle=paste0("Number of responses is indicated in the box")
      
    )
  
})

```


<!-- Compare by Question -->

<!-- Summary  -->
<!-- ============================================================ -->
<!-- # Overall performance -->
<!-- # Smmary -->


### Org. Chart view
<!-- Track by Org. Chart  -->




```{r echo=FALSE, results='asis'}

if (T){
  
  
  #renderPlot({
  renderPrint({
    
    if (id1() == 0 ) {
      cat("Org. Chart for entire Public Service is too long.\n Please shorten it by selecting specific Agency or Department")
    } else {
      
      # dt <- dtRESULT[ , .(ORG_1, ORG_2,ORG_3,ORG_4, SCORE100, sep = "/")][, pathString:=paste(ORG_1, ORG_2,ORG_3,ORG_4, SCORE100, sep = "/")] 
      # 
      # dtRESULTtree <- as.Node(dt)
      # rm(dt)
      # print(dtRESULTtree, limit=NULL) 
      # plot(dtRESULTtree)  does notwork in Shiny :(  
      # but works off-line
      
      
      r.dtRESULT()[ , .(ORG_1, ORG_2,ORG_3,ORG_4, SCORE100, sep = "/")][
        , pathString:=paste(ORG_1, ORG_2,ORG_3,ORG_4, SCORE100, sep = "/")] %>%
        as.Node() %>% print(limit=NULL) 
      
      
      
      
      
    }
  })
  
}

```  


### Tabulated summary
<!-- ### Summary results: tabulated  -->

#### Selection:
```{r summary.deptnames}

# renderPrint({
#   input$yearsToShow
# })


renderText({
  #setkeyv(dtDepartments,PSES_ID_COLS)
  #  dt <- dtDepartments[ as.list(myID)]
  dt <- dtDepartments[ as.list(r.myID() )]
  #   dt <- dtDepartments[ .(c(id1(),id2(),id3(),id4(),id5() ) )]
  sprintf("Department: %s (%s). ID=%i.%i.%i.%i.%i" , 
          dt$Organization, dt$pathString, 
          id1(),id2(),id3(),id4(),id5())
})


# renderText({
#   #paste0("Year: ", r.myYear()) 
#     paste0("Year: ", input$year) 
# 
# })


renderText({
  #dtQuestions[QUESTION==r.myQ()]$Question 
  #
  # paste0("Question ", input$question)
  paste0("", dtQuestions[Question.Abbreviated==input$question]$Question)
})



```

<!-- #### Summary: -->


<!-- NB: Table is interactive.  - To sort by a column, click on the column name. -->

```{r summary.tabulated}

DT::renderDataTable({
  
  DT::datatable(
    r.dtRESULT()[, .(IDlevel,pathString,SURVEYR,ANSCOUNT,
                     RANK_GoC, RANK_Agency,
                     SCORE100,   SCORE_vs_2011, SCORE_vs_2014)], #,   SCORE_vs_2011, SCORE_vs_2014
    options = list(
      # pageLength = 10,      
      bPaginate = T
      
    )
  )
})

```



### Tabulated details


<!-- #### Details -->

```{r}

DT::renderDataTable({
  
  DT::datatable(
    r.dtRESULT()[, .(IDlevel,pathString,SURVEYR,
                     SCORE100, 
                     ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5)],
    options = list(
      bPaginate = T,
      pageLength = 16
    )
  )
})

```


