---
#title: "iTrack: Public Service Employee Survey" 
title: "Public Service Employee Survey: Interactive Results Tracker" 
# author: "Interactive Results Tracker"
#date: "AADD (DDMMYY)" # 
# subtitle: "Interactive Report" # iTracker Interactive results tracker" DOES NOT SHOW !!
# author: "Generated by [iReport](https://o-canada.shinyapps.io/PSES)" 

output: 
  flexdashboard::flex_dashboard:
    orientation: rows #columns #  #__default columns__ rows columns
    social: menu
    #     social: [ "twitter", "facebook", "menu" ]
    vertical_layout: scroll # fill # scroll  #fill  #default fill
    # source_code: embed
    navbar:
      - { title: "iTrack", href: "https://itrack.shinyapps.io/PSES/", align: right }
runtime: shiny
---


```{r PSES-0-Globals.Rmd, child = 'PSES-0-Globals.Rmd'}
```

```{r app-specific-constants, include=FALSE, warning=FALSE, echo=F}

myQ <- "Q43"
myQs <- c("Q43", "Q42")
myYears <- c(2018)
myYear <- 2018

Rank.T <- 20

myBYPASS_SELECTION = TRUE
myID0 = myID.SE

myBYPASS_SELECTION = FALSE
myID0 = c(0,0,0,0,0)
myID = myID0
myLevel=getLevel(myID)


```


<!-- ```{r PSES-iTrack-0-Title.Rmd, child = 'PSES-iTrack-0-Title.Rmd'} -->
<!-- ``` -->

```{r PSES-1-Selection.Rmd, child = 'PSES-1-Selection.Rmd'}
```

```{r PSES-3-ByDept.Rmd, child = 'PSES-3-ByDept.Rmd'}
```

```{r PSES-2-ByQuestion.Rmd, child = 'PSES-2-ByQuestion.Rmd'}
```






# By Year

## Row 

<!-- Not enough data for selected Department. -->
Not enough data for selected Department.  Please contact the developer.

<!-- Not available in Light version. -    -->
<!-- Please conntact developer to obtain Full version. -->


<!-- ```{r PSES--byYear.Rmd, child = 'PSES-4-byYear.Rmd'} -->
<!-- ``` -->



```{r PSES--ai.Rmd, child = 'PSES-5-AI.Rmd'}
```

```{r PSES--report.Rmd, child = 'PSES-6-Report.Rmd'}
```



```{r PSES--end.Rmd, child = 'PSES-7-End.Rmd'}
```


```{r PSES--report.Rmd, child = 'PSES-8-FAQ.Rmd'}
```


```{r PSES--ReleaseNotes.Rmd, child = 'PSES-z-ReleaseNotes.Rmd'}
```


