
# Make selection: {.sidebar}



```{r input.dept, echo=F}


dept1 <- dtDepartments[LEVEL1ID!=0 &LEVEL2ID==0]$Organization %>% unique() %>% sort()

selectInput('level1', sprintf("Select Department (Total=%i)", dept1 %>% length), 
            choices = c(".ALL COMBINED.", dept1),
                        width="100%", 
            selected=".ALL COMBINED."
) 

id1 <- reactive({
  #dtDepartments[Organization %in% input$level1]$LEVEL1ID
  ifelse(input$level1==".ALL COMBINED.", 0, dtDepartments[Organization %in% input$level1]$LEVEL1ID)
})

renderUI({
  dept2 <- dtDepartments[LEVEL1ID == id1() & LEVEL2ID!=0 &  LEVEL2ID!=999 &  LEVEL3ID==0]$Organization %>% unique() %>%  sort()
  selectInput('level2', sprintf("Next level (Total=%i)", dept2 %>% length), 
              choices = c(".ALL COMBINED.", dept2),
              selected=".ALL COMBINED."
  )
})

id2<- reactive({
  #dtDepartments[Organization %in% input$level2]$LEVEL2ID
  ifelse(input$level2==".ALL COMBINED.", 0, dtDepartments[Organization %in% input$level2]$LEVEL2ID)
})

renderUI({
  dept3 <- dtDepartments[LEVEL1ID == id1() & LEVEL2ID == id2() &  LEVEL3ID!=0 & LEVEL4ID==0]$Organization %>% unique() %>% sort()
  selectInput('level3',  sprintf("Next Level (Total=%i)", dept3 %>% length), 
              choices = c(".ALL COMBINED.", dept3),
              selected=".ALL COMBINED."
  )
})


id3 <- reactive({
  ifelse(input$level3==".ALL COMBINED.", 0, dtDepartments[Organization %in% input$level3]$LEVEL3ID)
})

renderUI({
  dept4 <- dtDepartments[LEVEL1ID == id1() & LEVEL2ID == id2() & LEVEL3ID == id3() & LEVEL4ID!=0 & LEVEL5ID==0]$Organization %>% unique() %>% sort()
  selectInput('level4',  sprintf("Next Level (Total=%i)", dept4 %>% length), 
              choices = c(".ALL COMBINED.", dept4),
              selected=".ALL COMBINED."
  )
})


id4 <- reactive({
  ifelse(input$level4==".ALL COMBINED.", 0, dtDepartments[Organization %in% input$level4]$LEVEL4ID)
})


# ERROR HERE: Shows  dept5 %>% length = Total 1 ???
# TODO
if (F) {
  renderUI({
    dept5 <- dtDepartments[LEVEL1ID == id1() & LEVEL2ID == id2() & LEVEL3ID == id3() &  LEVEL4ID == id4() ]$Organization %>% unique() %>% sort()
    selectInput('level5', sprintf("Level 5. Total=%i", dept5 %>% length), 
                choices = c(".ALL COMBINED.", dept5),
                selected=".ALL COMBINED."
    )
  })
}


id5 <- reactive({
  0
  #ifelse(input$level5==".ALL COMBINED.", 0, dtDepartments[Organization %in% input$level5]$LEVEL5ID)
})


r.myID <- reactive({
  myID <<- c(id1(),id2(),id3(),id4(),id5())
  myID
})

r.myLevel <- reactive({
  myLevel <<-  getLevel(myID)
  myLevel
})

r.DeptSelected  <- reactive({
  selectDepts (id=r.myID())
   # selectDepts (id=c(id1(),id2(),id3(),id4(),id5()))
})

# r.dtAll <- reactive({
#   getRESULTS (id=c(id1(),id2(),id3(),id4(),id5()),
#               nQ = dtQuestions[Theme %in% input$theme]$QUESTION,
#               aYears=input$year)
# })

 r.dtRESULT <- reactive({ 
  #  TODO later
  # setkeyv(dtDepartments,PSES_ID_COLS)
  # dtRESULT <<- dtPSES[SURVEYR %in% input$year][
  #   r.DeptSelected(), on=PSES_ID_COLS][
  #     dtQuestions, on="QUESTION"]
  # 
  # setkeyv(dtRESULT, PSES_ID_COLS)
  # #q <- (dtRESULT$QUESTION %>% unique)[2];q
  # for (q in dtRESULT$QUESTION %>% unique) {
  #   myScore <- dtRESULT[as.list(myID)][QUESTION==q]$SCORE100; myScore
  #   myRank <- dtPSES[QUESTION==q &  SCORE100 > myScore, .N] ; myRank
  #   dtRESULT[QUESTION==q, ':=' (
  #     RANK=dtPSES[QUESTION==q & LEVEL1ID > 0 &  SCORE100 > myScore, .N],
  #     TOTAL=dtPSES[QUESTION==q & LEVEL1ID > 0, .N]       )
  #     ] [, RANK2:=round(RANK/TOTAL*100)]
  #   dtRESULT[QUESTION==q & IDlevel == 0, ':=' (RANK2=50)]
  # }
  
})




# r.year <- reactive({
#   input$year
# })
# 
# r.nQ <- reactive({
#   dtQuestions[Question.Abbreviated == input$question]$QUESTION
# })



```

```{r input.year, echo=F}
selectInput('year', 'Select Year',
            choices = c("2018", "2017", "2014", "2011", "2008" )
            # ,
            # selected= c("2018" ),
            # multiple=T
)

```



``` {r input.showbest_whattoplot}

if (F) {
  selectInput('showwhat', "Functions to plot",
              choices = c(
                "Performance by Question:", # S=f(Q | Dept,Year)",
                "Performance by Department",
                "Performance by Year"
                # "Question = F (Score),
                # "Performance by Department",
                # "Performance by Year"
              )
  )
  checkboxInput("showbest", 
                # "Show main contribitors (to score)", 
                "Detect the best", 
                value=F)
  checkboxInput("showworst", 
                # "Show outliers", 
                "Find the worst", 
                value=F)
}

```

```{r input.sortby}

radioButtons('sortby', "Sort:",
             choices = c("alphabetically", "by score"),
             selected = "by score",
             inline = T
)

# radioButtons('sortby', "Sort:",
#              choices = c("alphabetically", "by score", "by ranking", "by number of responses"),
#              inline = T
# )
```

<!-- #### Step 5. Select Automation -->


```{r input.showparentchildren}
# checkboxInput("showparents", 
#               "Show hierarchy results", 
#               value=F)
# checkboxInput("showchildren", 
#               "Show subdivisions results", 
#               value=F)

```

